import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://cgfcmsmwfwmkjfasvznl.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnZmNtc213Zndta2pmYXN2em5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE2Mjk2MjMsImV4cCI6MjA0NzIwNTYyM30.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnZmNtc213Zndta2pmYXN2em5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE2Mjk2MjMsImV4cCI6MjA0NzIwNTYyM30';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
